# Generated by Django 5.2.4 on 2025-08-19 10:01

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('vetements', 'Vêtements'), ('chaussures', 'Chaussures'), ('equipements', 'Équipements'), ('autre', 'Autre')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='annonces/%Y/%m/')),
                ('email', models.EmailField(max_length=254)),
                    ('phone', models.CharField(blank=True, max_length=30)),
                    ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_published', models.BooleanField(default=False)),
                ('publish_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('delete_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
