# Generated by Django 5.2.4 on 2025-08-19 11:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Prix en euros (0 pour gratuit)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
