# Generated by Django 5.2.4 on 2025-08-17 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='index.partenairessponsor')),
            ],
            options={
                'verbose_name': 'Lien du sponsor',
                'verbose_name_plural': 'Liens du sponsor',
                'ordering': ['id'],
            },
        ),
    ]
