# Generated by Django 5.2.4 on 2025-08-26 20:52

import index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_sponsorlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_tarifs', index.models.CustomCloudinaryField(max_length=255, verbose_name='image')),
            ],
            options={
                'verbose_name': 'Tarifs',
                'verbose_name_plural': 'Tarifs',
            },
        ),
    ]
