# Generated by Django 5.2.4 on 2025-08-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_tarifs'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipes',
            name='ordre',
            field=models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (0 = premier)"),
        ),
    ]
