# Generated by Django 5.2.4 on 2025-09-20 13:38

import index.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_equipes_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipes',
            name='photo',
            field=index.models.CustomCloudinaryField(blank=True, max_length=255, null=True, validators=[index.models.validate_image_or_svg], verbose_name='photo'),
        ),
    ]
