# Generated by Django 5.2.4 on 2025-08-09 17:05

import boutique.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('prix', models.FloatField(default=0.0)),
                ('description_principal', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('image', models.ImageField(null=True, upload_to='boutique/')),
            ],
            options={
                'verbose_name': 'Produits',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paniers des utilisateurs',
                'verbose_name_plural': 'Paniers des utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('infos', models.TextField(blank=True, null=True)),
                ('total', models.FloatField(default=0.0)),
                ('numero_commande', models.CharField(default=boutique.models.generate_order_number, max_length=10, unique=True)),
                ('statut', models.CharField(choices=[('en_attente', 'en attente'), ('en_cours', 'en préparation'), ('prete', 'prête'), ('recuperee', 'récuperée'), ('annulee', 'annulée')], default='en_attente', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commandes',
                'verbose_name_plural': 'Commandes',
            },
        ),
        migrations.CreateModel(
            name='ArticleCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_article', models.CharField(blank=True, max_length=150)),
                ('prix_article', models.FloatField(default=0.0)),
                ('quantite', models.IntegerField(default=1)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.commande')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boutique.produits')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='produits_commandes',
            field=models.ManyToManyField(through='boutique.ArticleCommande', to='boutique.produits'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.produits')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='product_cart',
            field=models.ManyToManyField(through='boutique.CartItem', to='boutique.produits'),
        ),
    ]
