# Generated by Django 5.2.4 on 2025-08-09 17:27

import cloudinary_storage.storage
import index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarrousselImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', index.models.CustomCloudinaryField(max_length=255, validators=[index.models.validate_image_or_svg], verbose_name='image')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('titre', models.CharField(blank=True, max_length=100)),
                ('sous_titre', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('texte_bouton', models.CharField(blank=True, max_length=50)),
                ('lien_bouton', models.URLField(blank=True)),
                ('lien_interne', models.CharField(blank=True, max_length=100)),
                ('position_texte', models.CharField(choices=[('center', 'Centre'), ('left', 'Gauche'), ('right', 'Droite'), ('bottom-left', 'Bas gauche'), ('bottom-right', 'Bas droite'), ('top-left', 'Haut gauche'), ('top-right', 'Haut droite')], default='center', max_length=20)),
                ('couleur_texte', models.CharField(choices=[('white', 'Blanc'), ('black', 'Noir'), ('primary', 'Couleur primaire')], default='white', max_length=20)),
                ('opacite_overlay', models.FloatField(default=0.4)),
                ('vitesse_slider', models.PositiveIntegerField(default=800)),
            ],
            options={
                'verbose_name': 'Défilement images',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='DocumentsDossierInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('document', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='inscriptions/documents-dossier-inscr/')),
            ],
            options={
                'verbose_name': 'Documents inscription',
                'verbose_name_plural': 'Documents inscription',
            },
        ),
        migrations.CreateModel(
            name='DocumentsFonctionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('fichier', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='informations/fonctionnement/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documents de fonctionnement',
                'verbose_name_plural': 'Documents de fonctionnement',
            },
        ),
        migrations.CreateModel(
            name='Entrainement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_entrainement', index.models.CustomCloudinaryField(max_length=255, verbose_name='image')),
            ],
            options={
                'verbose_name': 'Planning entraînement',
                'verbose_name_plural': 'Planning entraînement',
            },
        ),
        migrations.CreateModel(
            name='Equipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('coach', models.CharField(max_length=100)),
                ('coach_adjoint', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name': 'Équipes',
                'verbose_name_plural': 'Équipes',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
                ('reponse', models.TextField(max_length=1000)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (0 = premier)")),
            ],
            options={
                'verbose_name': 'Partie FAQ',
                'verbose_name_plural': 'Partie FAQ',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Organisation_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_profile', index.models.CustomCloudinaryField(blank=True, max_length=255, null=True, validators=[index.models.validate_image_or_svg], verbose_name='image')),
                ('nom', models.CharField(max_length=150)),
                ('fonction', models.CharField(max_length=250)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Organigramme bureau',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='PartenairesSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_blanc', index.models.CustomCloudinaryField(blank=True, max_length=255, validators=[index.models.validate_image_or_svg], verbose_name='image')),
                ('image_noir', index.models.CustomCloudinaryField(blank=True, max_length=255, validators=[index.models.validate_image_or_svg], verbose_name='image')),
                ('nom', models.CharField(max_length=150)),
                ('fonction', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Partenaires et sponsors',
            },
        ),
    ]
