# Generated by Django 5.1.3 on 2025-08-04 18:19

import index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarrousselImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accueil/caroussel/')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (0 = premier)")),
                ('titre', models.CharField(blank=True, help_text="Titre affiché sur l'image", max_length=100)),
                ('sous_titre', models.CharField(blank=True, help_text="Sous-titre affiché sur l'image", max_length=200)),
                ('description', models.TextField(blank=True, help_text="Description affichée sur l'image", max_length=300)),
                ('texte_bouton', models.CharField(blank=True, help_text="Texte du bouton (ex: 'En savoir plus')", max_length=50)),
                ('lien_bouton', models.URLField(blank=True, help_text='URL externe vers laquelle le bouton redirige')),
                ('lien_interne', models.CharField(blank=True, help_text="Nom de l'URL Django (ex: 'index:equipes')", max_length=100)),
                ('position_texte', models.CharField(choices=[('center', 'Centre'), ('left', 'Gauche'), ('right', 'Droite'), ('bottom-left', 'Bas gauche'), ('bottom-right', 'Bas droite'), ('top-left', 'Haut gauche'), ('top-right', 'Haut droite')], default='center', help_text="Position du texte sur l'image", max_length=20)),
                ('couleur_texte', models.CharField(choices=[('white', 'Blanc'), ('black', 'Noir'), ('primary', 'Couleur primaire')], default='white', help_text='Couleur du texte', max_length=20)),
                ('opacite_overlay', models.FloatField(default=0.4, help_text='Opacité du fond sombre (0.0 = transparent, 1.0 = opaque)')),
                ('vitesse_slider', models.PositiveIntegerField(default=800, help_text='Durée de transition entre les slides en millisecondes', verbose_name='Vitesse du slider (ms)')),
            ],
            options={
                'verbose_name': 'Défilement images',
                'verbose_name_plural': 'Défilement images',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='DocumentsDossierInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='inscriptions/documents-dossier-inscr/')),
            ],
            options={
                'verbose_name': 'Documents inscription',
                'verbose_name_plural': 'Documents inscription',
            },
        ),
        migrations.CreateModel(
            name='DocumentsFonctionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('fichier', models.FileField(upload_to='informations/fonctionnement/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documents de fonctionnement',
                'verbose_name_plural': 'Documents de fonctionnement',
            },
        ),
        migrations.CreateModel(
            name='Entrainement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_entrainement', models.ImageField(upload_to='informations/entraînements/')),
            ],
            options={
                'verbose_name': 'Planning entraînement',
                'verbose_name_plural': 'Planning entraînement',
            },
        ),
        migrations.CreateModel(
            name='Equipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('coach', models.CharField(max_length=100)),
                ('coach_adjoint', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name': 'Équipes',
                'verbose_name_plural': 'Équipes',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
                ('reponse', models.TextField(max_length=1000)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (0 = premier)")),
            ],
            options={
                'verbose_name': 'Partie FAQ',
                'verbose_name_plural': 'Partie FAQ',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Organisation_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_profile', models.ImageField(blank=True, null=True, upload_to='presentation/organisation/')),
                ('nom', models.CharField(max_length=150)),
                ('fonction', models.CharField(max_length=250)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (0 = premier)")),
            ],
            options={
                'verbose_name': 'Organigramme bureau',
                'verbose_name_plural': 'Organigramme bureau',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='PartenairesSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_blanc', index.models.CustomImageField(blank=True, help_text='Logo blanc/transparent - pour footer et barre défilante (Formats acceptés : JPG, PNG, GIF, BMP, WebP, SVG)', upload_to='informations/part-spons/blanc/', validators=[index.models.validate_image_or_svg, index.models.validate_image_or_svg])),
                ('image_noir', index.models.CustomImageField(blank=True, help_text='Logo noir/coloré - pour page informations (Formats acceptés : JPG, PNG, GIF, BMP, WebP, SVG)', upload_to='informations/part-spons/noir/', validators=[index.models.validate_image_or_svg, index.models.validate_image_or_svg])),
                ('nom', models.CharField(max_length=150)),
                ('fonction', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Partenaires et sponsors',
                'verbose_name_plural': 'Partenaires et sponsors',
            },
        ),
    ]
